# identifiant_route
#     path: url d'acces
#     controller : App\Controller\LeControlleur::methode associé à la route

index:
  path: /
  controller: App\Controller\PageController::index

portfolio:
  path: /portfolio
  controller: App\Controller\PageController::portfolio

contact:
  path: /contact
  controller: App\Controller\PageController::contact

admin:
  path: /admin
  controller: App\Controller\PageController::admin

portfolio-item:
  path: /portfolio/{id}-{title}
  controller: App\Controller\PageController::portfolio_item
  requirements:
    id: '\d+'
