# identifiant_route
#     path: url d'acces
#     controller : App\Controller\LeControlleur::methode associé à la route

index:
  path: /
  controller: App\Controller\PageController::index


contact:
  path: /contact
  controller: App\Controller\PageController::contact

admin:
  path: /admin
  controller: App\Controller\PageController::admin


############################
#       PORTFOLIO
############################
portfolio-project:
  path: /portfolio/{id}-{title}
  controller: App\Controller\PortfolioController::portfolio_project
  requirements:
    id: '\d+'

portfolio:
  path: /portfolio
  controller: App\Controller\PortfolioController::portfolio

portfolio-add:
  path: /admin/portfolio/add
  controller: App\Controller\PortfolioController::portolio_add